apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: mlflow-pvc
          persistentVolumeClaim:
            claimName: mlflow-pvc
        - name: minio-initdb
          configMap:
            name: minio-initdb-config
            defaultMode: 0777
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
          volumeMounts:
            - name: mlflow-pvc
              mountPath: '/data'
            - name: minio-initdb
              mountPath: '/init'
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              value: "minio123"
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "500m"
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 256Mi
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", '/init/init.sh' ]
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio-service
spec:
  ports:
    - port: 9000
      name: s3
  selector:
    app: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-initdb-config
data:
  init.sh: |
    echo 'Waiting starting'
    sleep 10
    mc alias set minio http://127.0.0.1:9000 minio minio123
    mc mb minio/mlflow