apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # The sql_alchemy_conn value is a base64 encoded representation of this connection string:
  # postgresql+psycopg2://ktoairflow:ktomlops@postgres-airflow:5432/airflow
  # sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2t0b2FpcmZsb3c6a3RvbWxvcHNAcG9zdGdyZXMtYWlyZmxvdzo1NDMyL2FpcmZsb3c=
  # mysql connection string mysql+mysqldb://ktoairflow:ktomlops@mysql:3306/airflow
  sql_alchemy_conn: bXlzcWwrbXlzcWxkYjovL2t0b2FpcmZsb3c6a3RvbWxvcHNAbXlzcWw6MzMwNi9haXJmbG93