apiVersion: "route.openshift.io/v1"
kind: Route
metadata:
  name: airflow
spec:
  host: ""
  path: ""
  port:
    targetPort: 8080
  tls: null
  to:
    kind: Service
    name: airflow
    weight: 100